# Generated by Django 3.0.7 on 2020-07-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Picture',
            field=models.ImageField(upload_to='myproducts/'),
        ),
    ]
